branches:
  only:
  - master
  - major
  - stable
  - latest
  - /^\d+\.\d+(\.\d+)?(-\S*)?$/
  - /^release\/\d+\.\d+\.x$/

git:
  depth: false

env:
  global:
    - FULL_RUN=$(if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then echo "fullRun"; else echo ""; fi)
    - TARGET_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "origin/$TRAVIS_BRANCH^"; else echo "origin/$TRAVIS_BRANCH"; fi)
    - CURRENT_BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" = "false" ]; then echo "origin/$TRAVIS_BRANCH"; else echo "origin/$TRAVIS_PULL_REQUEST_BRANCH"; fi)

jobs:
  exclude:
    - language: ruby
  include:
    - name: Chrome (Linux)
      os: linux
      dist: xenial
      language: node_js
      node_js: 10
      services:
        - xvfb
      addons:
        chrome: stable
      before_script:
        - echo $TRAVIS_EVENT_TYPE
        # Setup xvfb
        - 'export DISPLAY=:99.0'
        - 'sleep 3'
        # Setup CKEditor 4 testing environment
        - pwd
        - npm install benderjs-cli -g
        - npm i
        # Setup bender test runner
        - cd ..
        - pwd
        - git clone https://github.com/ckeditor/ckeditor4-benderjs-runner.git
        - cd ckeditor4-benderjs-runner
        - npm i
      script:
        - pwd
        - echo "Running tests based on diff between $TARGET_BRANCH and $CURRENT_BRANCH"
        - npm run start "../../ckeditor4/bender-runner.config.json" "$TARGET_BRANCH" "$CURRENT_BRANCH" "chrome" "$FULL_RUN"

    - name: Firefox (Linux)
      os: linux
      dist: xenial
      language: node_js
      node_js: 10
      services:
        - xvfb
      addons:
        firefox: latest
      before_script:
        - echo $TRAVIS_EVENT_TYPE
        # Setup xvfb
        - 'export DISPLAY=:99.0'
        - 'sleep 3'
        # Setup CKEditor 4 testing environment
        - pwd
        - npm install benderjs-cli -g
        - npm i
        # Setup bender test runner
        - cd ..
        - pwd
        - git clone https://github.com/ckeditor/ckeditor4-benderjs-runner.git
        - cd ckeditor4-benderjs-runner
        - npm i
      script:
        - pwd
        - echo "Running tests based on diff between $TARGET_BRANCH and $CURRENT_BRANCH"
        - npm run start "../../ckeditor4/bender-runner.config.json" "$TARGET_BRANCH" "$CURRENT_BRANCH" "firefox" "$FULL_RUN"
